# Generated by Django 4.2.2 on 2023-07-03 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="studio",
            new_name="studios",
        ),
    ]
