# Generated by Django 4.2.2 on 2023-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0004_episode_episoderole_episodecast_episode_cast_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="cast",
            new_name="casts",
        ),
        migrations.AddField(
            model_name="episode",
            name="romanized_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
