# Generated by Django 5.0 on 2024-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0011_alter_location_current_identity"),
        ("watch", "0004_add_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="filming_locations",
            field=models.ManyToManyField(
                blank=True, related_name="movies_filmed_here", to="visit.location"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="setting_locations",
            field=models.ManyToManyField(
                blank=True, related_name="movies_set_here", to="visit.location"
            ),
        ),
    ]
