# Generated by Django 5.0 on 2024-01-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0005_movie_filming_locations_movie_setting_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmovie",
            name="filming_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmovie",
            name="setting_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="filming_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="setting_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
