# Generated by Django 4.2.2 on 2023-07-04 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watch", "0005_rename_cast_episode_casts_episode_romanized_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_watch", "To Watch"),
                            ("watching", "Watching"),
                            ("watched", "Watched"),
                            ("paused", "Paused"),
                            ("abandoned", "Abandoned"),
                            ("rewatching", "Rewatching"),
                            ("rewatched", "Rewatched"),
                        ],
                        max_length=255,
                    ),
                ),
                ("share_to_feed", models.BooleanField(default=False)),
                ("content", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("progress", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "progress_type",
                    models.CharField(
                        choices=[("TM", "Time(s)"), ("EP", "Episode")],
                        default="TM",
                        max_length=2,
                    ),
                ),
                ("comments_enabled", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="write.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
