# Generated by Django 5.0.1 on 2024-01-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0012_historicallocation_osm_id_location_osm_id"),
        ("watch", "0006_historicalmovie_filming_locations_hierarchy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="filming_locations",
            field=models.ManyToManyField(
                blank=True, related_name="episodes_filmed_here", to="visit.location"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="filming_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="setting_locations",
            field=models.ManyToManyField(
                blank=True, related_name="episodes_set_here", to="visit.location"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="setting_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="filming_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="setting_locations_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
