# Generated by Django 5.0.1 on 2024-01-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0004_historicalwork_setting_locations_hierarchy_and_more"),
        ("read", "0007_delete_historicalissueinstance"),
        ("watch", "0007_episode_filming_locations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmovie",
            name="based_on",
        ),
        migrations.RemoveField(
            model_name="historicalseries",
            name="based_on",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="based_on",
        ),
        migrations.RemoveField(
            model_name="series",
            name="based_on",
        ),
        migrations.AddField(
            model_name="movie",
            name="based_on_games",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="play.work"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="based_on_litworks",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="read.work"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="based_on_movies",
            field=models.ManyToManyField(blank=True, to="watch.movie"),
        ),
        migrations.AddField(
            model_name="movie",
            name="based_on_series",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="watch.series"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="based_on_games",
            field=models.ManyToManyField(
                blank=True, related_name="series", to="play.work"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="based_on_litworks",
            field=models.ManyToManyField(
                blank=True, related_name="series", to="read.work"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="based_on_movies",
            field=models.ManyToManyField(
                blank=True, related_name="series", to="watch.movie"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="based_on_series",
            field=models.ManyToManyField(blank=True, to="watch.series"),
        ),
    ]
