# Generated by Django 4.2.2 on 2023-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0008_movie_based_on_series_based_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="watchcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_watch", "To Watch"),
                    ("watching", "Watching"),
                    ("watched", "Watched"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("rewatching", "Rewatching"),
                    ("rewatched", "Rewatched"),
                    ("Afterthoughts", "Afterthoughts"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="watch.genre"
            ),
        ),
    ]
