# Generated by Django 5.0.1 on 2024-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0008_remove_historicalmovie_based_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="based_on_movies",
            field=models.ManyToManyField(
                blank=True, related_name="related_movies", to="watch.movie"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="based_on_series",
            field=models.ManyToManyField(
                blank=True, related_name="related_series", to="watch.series"
            ),
        ),
    ]
