# Generated by Django 4.2.2 on 2023-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0010_series_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studio",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
