# Generated by Django 4.2.2 on 2023-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0011_studio_wikipedia_alter_studio_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="closed_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studio",
            name="founded_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
