# Generated by Django 5.0.1 on 2024-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0009_alter_historicalreleasetrack_disk_and_more"),
        ("watch", "0012_episode_based_on_games_episode_based_on_litworks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="ending_songs",
            field=models.ManyToManyField(
                blank=True, related_name="episodes_as_ending_song", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="theme_songs",
            field=models.ManyToManyField(
                blank=True, related_name="episodes_as_theme_song", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="episodes_featuring_track", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="ending_songs",
            field=models.ManyToManyField(
                blank=True, related_name="movies_as_ending_song", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="soundtracks",
            field=models.ManyToManyField(
                blank=True, related_name="movies_with_soundtrack", to="listen.release"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="theme_songs",
            field=models.ManyToManyField(
                blank=True, related_name="movies_as_theme_song", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="movies_featuring_track", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="soundtracks",
            field=models.ManyToManyField(
                blank=True, related_name="series_with_soundtrack", to="listen.release"
            ),
        ),
    ]
