# Generated by Django 4.2.2 on 2023-08-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0013_movie_wikipedia_series_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
