# Generated by Django 5.0.1 on 2024-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0013_episode_ending_songs_episode_theme_songs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmovie",
            name="official_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalseries",
            name="official_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="official_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="official_website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
