# Generated by Django 5.0.1 on 2024-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0011_alter_creator_active_years_and_more"),
        ("watch", "0014_historicalmovie_official_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="stars",
            field=models.ManyToManyField(
                blank=True, related_name="movies_starred", to="entity.creator"
            ),
        ),
    ]
