# Generated by Django 5.0.1 on 2024-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0016_series_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
