# Generated by Django 4.2.2 on 2023-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0017_remove_studio_romanized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="imdb",
            field=models.URLField(blank=True, null=True),
        ),
    ]
