# Generated by Django 5.0.1 on 2024-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0017_episode_notes_historicalepisode_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalseries",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("continuing", "Continuing"),
                    ("season-ended", "Season Ended"),
                    ("ended", "Series Ended"),
                    ("canceled", "Canceled"),
                    ("hiatus", "On Hiatus"),
                    ("renewed", "Renewed"),
                    ("limbo", "In Limbo"),
                ],
                default="ended",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("continuing", "Continuing"),
                    ("season-ended", "Season Ended"),
                    ("ended", "Series Ended"),
                    ("canceled", "Canceled"),
                    ("hiatus", "On Hiatus"),
                    ("renewed", "Renewed"),
                    ("limbo", "In Limbo"),
                ],
                default="ended",
                max_length=20,
                null=True,
            ),
        ),
    ]
