# Generated by Django 5.0.1 on 2024-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0018_historicalseries_status_series_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="imdb",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="imdb",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
