# Generated by Django 5.0.1 on 2024-06-18 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0019_episode_imdb_episode_wikipedia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="watchcheckin",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PU", "Public"),
                    ("ME", "Mentioned"),
                    ("FO", "Followers"),
                    ("PR", "Private"),
                ],
                default="PU",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="watchcheckin",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="visible_watch_checkins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
