# Generated by Django 4.2.2 on 2023-08-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("watch", "0019_collection_seriesincollection_movieincollection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentInCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="seriesincollection",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="seriesincollection",
            name="series",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="movies",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="series",
        ),
        migrations.DeleteModel(
            name="MovieInCollection",
        ),
        migrations.DeleteModel(
            name="SeriesInCollection",
        ),
        migrations.AddField(
            model_name="contentincollection",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="watch.collection",
            ),
        ),
        migrations.AddField(
            model_name="contentincollection",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
