# Generated by Django 4.2.2 on 2023-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0021_rename_history_studio_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="note",
        ),
    ]
