# Generated by Django 4.2.2 on 2023-09-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0011_company"),
        ("watch", "0022_remove_studio_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="studios_deprecated",
            field=models.ManyToManyField(related_name="movies", to="watch.studio"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="studios",
            field=models.ManyToManyField(related_name="movies", to="entity.company"),
        ),
    ]
