# Generated by Django 4.2.2 on 2023-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0011_company"),
        ("watch", "0024_series_studios_deprecated_alter_series_studios"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="distributors",
            field=models.ManyToManyField(
                related_name="movies_distributed", to="entity.company"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="distributors",
            field=models.ManyToManyField(
                related_name="series_distributed", to="entity.company"
            ),
        ),
    ]
