# Generated by Django 5.1 on 2024-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0024_migrate_episode_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodecast",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisodecast",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalmoviecast",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
