# Generated by Django 4.2.2 on 2023-09-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0025_movie_distributors_series_distributors"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieReleaseDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_release_dates",
                        to="watch.movie",
                    ),
                ),
            ],
        ),
    ]
