# Generated by Django 5.1 on 2024-10-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0025_episodecast_alt_name_historicalepisodecast_alt_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodecast",
            name="is_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="episodecast",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisodecast",
            name="is_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalepisodecast",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmoviecast",
            name="is_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalmoviecast",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="is_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moviecast",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
