# Generated by Django 4.2.2 on 2023-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0026_moviereleasedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
    ]
