# Generated by Django 4.2.2 on 2023-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0027_remove_movie_release_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="description",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="description",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="series",
            old_name="description",
            new_name="notes",
        ),
    ]
