# Generated by Django 4.2.2 on 2023-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0028_rename_description_collection_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="episodecast",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="episoderole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="moviecast",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="movierole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="series",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="seriesrole",
            old_name="person",
            new_name="creator",
        ),
    ]
