# Generated by Django 4.2.2 on 2023-10-18 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0029_rename_persons_episode_creators_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="studios_deprecated",
        ),
        migrations.RemoveField(
            model_name="series",
            name="studios_deprecated",
        ),
        migrations.DeleteModel(
            name="Studio",
        ),
    ]
