# Generated by Django 4.2.2 on 2023-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0030_remove_movie_studios_deprecated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="episode",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="series",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
