# Generated by Django 4.2.2 on 2023-10-30 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0031_collection_locked_episode_locked_movie_locked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="romanized_title",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="romanized_title",
        ),
        migrations.RemoveField(
            model_name="series",
            name="romanized_title",
        ),
    ]
