# Generated by Django 5.0 on 2023-12-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0003_alter_historicallocation_level_alter_location_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="current_identity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="current_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current",
                to="visit.location",
            ),
        ),
    ]
