# Generated by Django 5.0 on 2023-12-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0004_historicallocation_current_identity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallocation",
            name="level",
            field=models.CharField(
                choices=[
                    ("continent", "Continent"),
                    ("polity", "Polity"),
                    ("region", "Region / State / Province / Canton / Prefecture"),
                    ("city", "City / Municipality / County"),
                    ("town", "Town / Township"),
                    ("village", "Village"),
                    ("district", "District"),
                    ("poi", "Point of Interest"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="level",
            field=models.CharField(
                choices=[
                    ("continent", "Continent"),
                    ("polity", "Polity"),
                    ("region", "Region / State / Province / Canton / Prefecture"),
                    ("city", "City / Municipality / County"),
                    ("town", "Town / Township"),
                    ("village", "Village"),
                    ("district", "District"),
                    ("poi", "Point of Interest"),
                ],
                max_length=20,
            ),
        ),
    ]
