# Generated by Django 5.0 on 2023-12-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0005_alter_historicallocation_level_alter_location_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
