# Generated by Django 5.0 on 2024-01-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0008_alter_historicallocation_level_alter_location_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="level_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="level_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicallocation",
            name="level",
            field=models.CharField(
                choices=[
                    ("level0", "Level 0"),
                    ("level1", "Level 1"),
                    ("level2", "Level 2"),
                    ("level3", "Level 3"),
                    ("level4", "Level 4"),
                    ("level5", "Level 5"),
                    ("level6", "Level 6"),
                    ("level7", "Level 7"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="level",
            field=models.CharField(
                choices=[
                    ("level0", "Level 0"),
                    ("level1", "Level 1"),
                    ("level2", "Level 2"),
                    ("level3", "Level 3"),
                    ("level4", "Level 4"),
                    ("level5", "Level 5"),
                    ("level6", "Level 6"),
                    ("level7", "Level 7"),
                ],
                max_length=20,
            ),
        ),
    ]
