# Generated by Django 5.0 on 2024-01-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0010_migrate_existing_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="current_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical_identity",
                to="visit.location",
            ),
        ),
    ]
