# Generated by Django 5.0.1 on 2024-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0011_alter_location_current_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="osm_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="osm_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
