# Generated by Django 5.0.1 on 2024-01-08 18:45

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("visit", "0012_historicallocation_osm_id_location_osm_id"),
        ("write", "0003_webmention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_visit", "To visit"),
                            ("visiting", "visiting"),
                            ("visited", "visited"),
                            ("revisiting", "Revisiting"),
                            ("revisited", "Revisited"),
                            ("living here", "Living here"),
                            ("lived there", "Lived there"),
                            ("afterthoughts", "Afterthoughts"),
                        ],
                        max_length=255,
                    ),
                ),
                ("share_to_feed", models.BooleanField(default=False)),
                ("content", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("progress", models.IntegerField(blank=True, null=True)),
                (
                    "progress_type",
                    models.CharField(
                        choices=[("ST", "Stayed Time")], default="ST", max_length=2
                    ),
                ),
                ("comments_enabled", models.BooleanField(default=True)),
                (
                    "content_type",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="write.tag")),
                (
                    "user",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
