# Generated by Django 5.0.1 on 2024-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0014_alter_visitcheckin_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_visit", "To visit"),
                    ("visiting", "Visiting"),
                    ("visited", "Visited"),
                    ("revisiting", "Revisiting"),
                    ("revisited", "Revisited"),
                    ("living-here", "Live here"),
                    ("lived-there", "Lived there"),
                    ("afterthoughts", "Afterthoughts"),
                ],
                max_length=255,
            ),
        ),
    ]
