# Generated by Django 5.0.1 on 2024-01-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0015_alter_visitcheckin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="osm_id_type",
            field=models.CharField(
                blank=True,
                choices=[("node", "Node"), ("way", "Way"), ("relation", "Relation")],
                default="relation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="osm_id_type",
            field=models.CharField(
                blank=True,
                choices=[("node", "Node"), ("way", "Way"), ("relation", "Relation")],
                default="relation",
                max_length=20,
                null=True,
            ),
        ),
    ]
