# Generated by Django 4.2.2 on 2023-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="LbvsBG9x", max_length=100, unique=True),
        ),
    ]
