# Generated by Django 4.2.2 on 2023-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
