# Generated by Django 5.0 on 2023-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enable_webmentions",
            field=models.BooleanField(default=False),
        ),
    ]
