# Generated by Django 4.2.2 on 2023-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_bio_alter_invitationcode_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(default="P9294mG3", max_length=100, unique=True),
        ),
    ]
