# Generated by Django 5.0 on 2023-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_enable_webmentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enable_replies_by_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="enable_share_to_feed_by_default",
            field=models.BooleanField(default=False),
        ),
    ]
