# Generated by Django 4.1.7 on 2023-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_bio_customuser_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
