# Generated by Django 4.2.2 on 2023-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_invitationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationrequest",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
    ]
