# Generated by Django 5.0 on 2023-12-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_webmention"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmention",
            name="author_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webmention",
            name="author_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="webmention",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webmention",
            name="mention_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("repost", "Repost"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
