# Generated by Django 4.2.2 on 2023-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_invitationrequest_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pure_text_mode",
            field=models.BooleanField(default=True),
        ),
    ]
