# Generated by Django 5.0 on 2023-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_webmention_author_name_webmention_author_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmention",
            name="content_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webmention",
            name="content_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="mention_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("comment", "Comment"),
                    ("repost", "Repost"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
