# Generated by Django 4.2.2 on 2023-09-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_pure_text_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pure_text_mode",
            field=models.BooleanField(default=False),
        ),
    ]
