# Generated by Django 5.0 on 2023-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_webmention_content_title_webmention_content_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webmention",
            name="author_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="content_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
