# Generated by Django 5.0 on 2023-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_webmention_author_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmention",
            name="author_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="author_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="content_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
