# Generated by Django 5.0 on 2023-12-29 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0009_webmention_author_handle_alter_webmention_author_url_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebMention",
        ),
    ]
