# Generated by Django 4.2.2 on 2023-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_mastodonaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueskyaccount",
            name="bluesky_pds_url",
            field=models.URLField(
                default="https://bsky.social",
                help_text="URL of your Personal Data Server (PDS).",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
