# Generated by Django 5.0.1 on 2024-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_webauthncredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="webauthncredential",
            name="key_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webauthncredential",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
