# Generated by Django 4.2.2 on 2023-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_blueskyaccount_bluesky_pds_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blueskyaccount",
            name="bluesky_pds_url",
            field=models.URLField(max_length=255),
        ),
    ]
