# Generated by Django 5.0.1 on 2024-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_webauthncredential_key_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webauthncredential",
            name="aaguid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
