# Generated by Django 5.0.1 on 2024-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_webauthncredential_aaguid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="enable_webmentions",
        ),
    ]
