# Generated by Django 4.2.2 on 2023-11-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_delete_fediversefollower"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enable_federation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="public_key",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="FediverseFollower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_uri", models.URLField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
