# Generated by Django 5.0.1 on 2024-04-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_blacklisteddomain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="enable_alt_profile",
        ),
    ]
