# Generated by Django 4.2.2 on 2023-11-16 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0015_customuser_enable_federation_customuser_public_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fediversefollower",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
