# Generated by Django 4.2.2 on 2023-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_fediversefollower_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fediversefollower",
            name="preferred_headers",
            field=models.TextField(blank=True, null=True),
        ),
    ]
