# Generated by Django 4.2.2 on 2023-11-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_fediversefollower_preferred_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="fediversefollower",
            name="follower_inbox",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fediversefollower",
            name="follower_shared_inbox",
            field=models.URLField(blank=True, null=True),
        ),
    ]
