# Generated by Django 5.1 on 2024-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_blockedip"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("limited", "Limited"),
                    ("logged_in_only", "Logged-in Only"),
                ],
                default="logged_in_only",
                max_length=15,
            ),
        ),
    ]
