# Generated by Django 4.2.2 on 2023-12-05 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_fediversefollower_follower_inbox_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="enable_federation",
        ),
        migrations.DeleteModel(
            name="FediverseFollower",
        ),
    ]
