# Generated by Django 5.0 on 2023-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_alter_apppassword_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="alt_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="custom_domain",
            field=models.URLField(blank=True, null=True),
        ),
    ]
