# Generated by Django 5.0 on 2023-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_customuser_alt_profile_customuser_custom_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
