# Generated by Django 5.0 on 2023-12-08 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_customuser_custom_domain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="alt_profile",
            new_name="enable_alt_profile",
        ),
    ]
