# Generated by Django 4.2.2 on 2023-06-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0001_initial"),
        ("write", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repost",
            name="original_activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="activity_feed.activity",
            ),
        ),
    ]
