# Generated by Django 5.0 on 2023-12-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0002_pin_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.URLField(max_length=2048)),
                ("target", models.URLField(max_length=2048)),
                ("verified", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("author_url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "author_handle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("comment", "Comment"),
                            ("repost", "Repost"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
