# Generated by Django 4.2.2 on 2023-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0003_remove_luvlist_content_type_remove_luvlist_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentinlist",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
