# Generated by Django 5.0.1 on 2024-01-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0003_webmention"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="items_per_page",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
