# Generated by Django 4.2.2 on 2023-06-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="say",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
