# Generated by Django 4.2.2 on 2023-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0004_alter_contentinlist_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentinlist",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentinlist",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
