# Generated by Django 5.0.1 on 2024-01-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0004_luvlist_items_per_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
