# Generated by Django 4.2.2 on 2023-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0005_pin_comments_enabled_post_comments_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="pin",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
        migrations.AddField(
            model_name="say",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
    ]
