# Generated by Django 5.0.1 on 2024-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0005_luvlist_short_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebMention",
        ),
    ]
