# Generated by Django 4.2.2 on 2023-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0006_luvlist_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
