# Generated by Django 4.2.2 on 2023-06-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0006_tag_pin_tags_post_tags_say_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
    ]
