# Generated by Django 4.2.2 on 2023-07-13 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0007_luvlist_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentinlist",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
