# Generated by Django 5.0.1 on 2024-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0007_album_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="album",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
        migrations.AddField(
            model_name="photo",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
    ]
