# Generated by Django 5.0.1 on 2024-06-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0008_album_comments_enabled_album_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_photo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="album_cover",
                to="write.photo",
            ),
        ),
    ]
