# Generated by Django 4.2.2 on 2023-08-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0009_luvlist_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="repost",
            name="original_repost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="write.repost",
            ),
        ),
    ]
