# Generated by Django 4.2.2 on 2023-09-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0010_repost_original_repost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Randomizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_generated_date", models.DateField(blank=True, null=True)),
                ("randomized_order", models.TextField(blank=True, null=True)),
                (
                    "last_generated_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="randomized_in",
                        to="write.contentinlist",
                    ),
                ),
                (
                    "luv_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="randomizer",
                        to="write.luvlist",
                    ),
                ),
            ],
        ),
    ]
