# Generated by Django 5.0.1 on 2024-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0010_say_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="say",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PU", "Public"),
                    ("ME", "Mentioned People Only"),
                    ("FO", "Followers Only"),
                    ("PR", "Private"),
                ],
                default="PU",
                max_length=2,
            ),
        ),
    ]
