# Generated by Django 5.0.1 on 2024-06-19 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0012_album_visibility_album_visible_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("PU", "Public"), ("PR", "Private")],
                default="PU",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True, related_name="visible_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
