# Generated by Django 4.2.2 on 2023-09-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0012_randomizer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randomizer",
            name="luv_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="randomizers",
                to="write.luvlist",
            ),
        ),
    ]
