# Generated by Django 4.2.2 on 2023-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0013_alter_randomizer_luv_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="randomizer",
            name="last_generated_date",
        ),
        migrations.AddField(
            model_name="randomizer",
            name="interval_in_seconds",
            field=models.IntegerField(default=86400),
        ),
        migrations.AddField(
            model_name="randomizer",
            name="last_generated_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
