# Generated by Django 4.2.2 on 2023-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0014_remove_randomizer_last_generated_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
