# Generated by Django 4.2.2 on 2023-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0015_luvlist_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
