# Generated by Django 5.0.1 on 2024-06-19 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0017_photo_visibility_photo_visible_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="visibility",
            field=models.CharField(
                choices=[("PU", "Public"), ("ME", "Mentioned People Only")],
                default="PU",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True, related_name="visible_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
