# Generated by Django 4.2.2 on 2023-10-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0017_say_is_direct_mention_say_visible_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, to="write.category"),
        ),
    ]
