# Generated by Django 4.2.2 on 2023-10-12 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0018_category_post_categories"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Project",
        ),
    ]
