# Generated by Django 5.0.1 on 2024-08-13 06:33

import autoslug.fields
import write.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0018_comment_visibility_comment_visible_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                editable=False,
                null=True,
                populate_from="title",
                slugify=write.models.custom_slugify,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                editable=False,
                null=True,
                populate_from="name",
                slugify=write.models.custom_slugify,
                unique=True,
            ),
        ),
    ]
