# Generated by Django 4.2.2 on 2023-10-12 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0019_rename_category_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="categories",
            new_name="projects",
        ),
    ]
