# Generated by Django 4.2.2 on 2023-10-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0020_rename_categories_post_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
    ]
