# Generated by Django 4.2.2 on 2023-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0022_rename_description_luvlist_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
