# Generated by Django 4.2.2 on 2023-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0027_remove_comment_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="repost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="say",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
