# Generated by Django 4.2.2 on 2023-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0028_comment_updated_at_pin_updated_at_post_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="order_preference",
            field=models.CharField(
                choices=[
                    ("ASC", "Ascending"),
                    ("DESC", "Descending"),
                    ("RAND", "Random"),
                ],
                default="ASC",
                max_length=4,
            ),
        ),
    ]
