# Generated by Django 4.2.2 on 2023-11-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0029_luvlist_order_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="luvlist",
            name="order_preference",
            field=models.CharField(
                choices=[("ASC", "Ascending"), ("DESC", "Descending")],
                default="ASC",
                max_length=4,
            ),
        ),
    ]
