# Generated by Django 4.2.2 on 2023-11-26 19:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0030_alter_luvlist_order_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
