# Generated by Django 4.2.2 on 2023-11-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0032_populate_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="share_to_feed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="share_to_feed",
            field=models.BooleanField(default=False),
        ),
    ]
