# Generated by Django 4.2.2 on 2023-11-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("write", "0035_populate_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.CharField(
                choices=[
                    ("NF", "Newest first"),
                    ("OF", "Oldest first"),
                    ("BT", "By title"),
                ],
                default="NF",
                max_length=2,
            ),
        ),
    ]
