# Generated by Django 4.2.2 on 2023-12-07 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("write", "0037_alter_comment_options_alter_contentinlist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="luvlist",
            name="allow_collaboration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="luvlist",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborated_luvlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
