# Generated by Django 4.2.2 on 2023-06-29 15:26

from django.db import migrations, models
import django.db.models.deletion
import listen.models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
        ("listen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="trackrole",
            old_name="name",
            new_name="alt_name",
        ),
        migrations.AddField(
            model_name="release",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=listen.models.rename_release_cover
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="cover_sens",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="romanized_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="WorkRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listen_workrole_set",
                        to="entity.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listen_workrole_set",
                        to="entity.role",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listen.work"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="work",
            name="persons",
            field=models.ManyToManyField(
                related_name="listen_works",
                through="listen.WorkRole",
                to="entity.person",
            ),
        ),
        migrations.CreateModel(
            name="TrackInRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_order", models.PositiveIntegerField()),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listen.release"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listen.track"
                    ),
                ),
            ],
            options={
                "ordering": ["track_order"],
            },
        ),
        migrations.AddField(
            model_name="release",
            name="tracks",
            field=models.ManyToManyField(
                related_name="releases",
                through="listen.TrackInRelease",
                to="listen.track",
            ),
        ),
    ]
