# Generated by Django 4.2.2 on 2023-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0002_work_rename_name_trackrole_alt_name_release_cover_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="language",
        ),
        migrations.AddField(
            model_name="track",
            name="length",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
