# Generated by Django 5.0 on 2023-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listencheckin",
            name="progress_type",
            field=models.CharField(
                choices=[
                    ("TT", "Accumulated Listen Time"),
                    ("LT", "Loop Time"),
                    ("EP", "Episode"),
                    ("TR", "Track"),
                ],
                default="LT",
                max_length=2,
            ),
        ),
    ]
