# Generated by Django 4.2.2 on 2023-06-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0004_release_genre_release_subtitle_track_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="release_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
