# Generated by Django 4.2.2 on 2023-06-30 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0005_work_release_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="relase_date",
            new_name="release_date",
        ),
    ]
