# Generated by Django 4.2.2 on 2023-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0006_rename_relase_date_track_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
