# Generated by Django 5.0.1 on 2024-01-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0006_add_created_by_to_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrelease",
            name="internet_archive_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="internet_archive_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
