# Generated by Django 5.0.1 on 2024-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0008_alter_historicalrelease_recording_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreleasetrack",
            name="disk",
            field=models.CharField(blank=True, default="1", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="releasetrack",
            name="disk",
            field=models.CharField(blank=True, default="1", max_length=10, null=True),
        ),
    ]
