# Generated by Django 5.0.1 on 2024-02-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listen", "0009_alter_historicalreleasetrack_disk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrelease",
            name="recording_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Studio", "Studio"),
                    ("Live", "Live"),
                    ("Studio and Live", "Studio and Live"),
                    ("Compilation", "Compilation"),
                    ("Bootleg", "Bootleg"),
                    ("Soundtrack", "Soundtrack"),
                    ("Mixtape", "Mixtape"),
                    ("Demo", "Demo"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="recording_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Studio", "Studio"),
                    ("Live", "Live"),
                    ("Studio and Live", "Studio and Live"),
                    ("Compilation", "Compilation"),
                    ("Bootleg", "Bootleg"),
                    ("Soundtrack", "Soundtrack"),
                    ("Mixtape", "Mixtape"),
                    ("Demo", "Demo"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
