# Generated by Django 4.2.2 on 2023-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0013_listencheckin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releasetrack",
            options={"ordering": ["disk", "order"]},
        ),
        migrations.AddField(
            model_name="releasetrack",
            name="disk",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
