# Generated by Django 4.2.2 on 2023-07-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0014_alter_releasetrack_options_releasetrack_disk"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="release_length",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
