# Generated by Django 4.2.2 on 2023-07-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0015_release_release_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="apple_music_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="spotify_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
