# Generated by Django 4.2.2 on 2023-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0017_release_note_track_note_work_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasetrack",
            name="alt_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
