# Generated by Django 4.2.2 on 2023-07-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0018_releasetrack_alt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasetrack",
            name="disk",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="releasetrack",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="releasetrack",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listen.track",
            ),
        ),
    ]
