# Generated by Django 4.2.2 on 2023-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0020_label_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
