# Generated by Django 4.2.2 on 2023-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0021_release_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="kkbox_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
