# Generated by Django 4.2.2 on 2023-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0023_alter_listencheckin_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="release",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="track",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="work",
            name="genre",
        ),
    ]
