# Generated by Django 4.2.2 on 2023-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0024_genre_remove_release_genre_remove_track_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="releases", to="listen.genre"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="tracks", to="listen.genre"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="listen_works", to="listen.genre"
            ),
        ),
    ]
