# Generated by Django 4.2.2 on 2023-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0025_release_genres_track_genres_work_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
