# Generated by Django 4.2.2 on 2023-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0027_release_wikipedia_work_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrole",
            name="alt_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
