# Generated by Django 4.2.2 on 2023-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0029_release_recording_type_alter_release_release_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="recording_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Studio", "Studio"),
                    ("Live", "Live"),
                    ("Studio and Live", "Studio and Live"),
                    ("Compilation", "Compilation"),
                    ("Box Set", "Box Set"),
                    ("Bootleg", "Bootleg"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="releasetrack",
            name="disk",
            field=models.CharField(default="1", max_length=10),
        ),
    ]
