# Generated by Django 4.2.2 on 2023-08-17 13:16

from django.db import migrations, models
import django.db.models.deletion
import listen.models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0030_alter_release_recording_type_alter_releasetrack_disk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("rss_feed_url", models.URLField(unique=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=listen.models.rename_release_cover,
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="podcasts", to="listen.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("length", models.CharField(blank=True, max_length=10, null=True)),
                ("audio_url", models.URLField()),
                ("episode_url", models.URLField(blank=True, null=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="listen.podcast",
                    ),
                ),
            ],
        ),
    ]
