# Generated by Django 4.2.2 on 2023-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0031_podcast_podcastepisode"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="episodes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="PodcastEpisode",
        ),
    ]
