# Generated by Django 4.2.2 on 2023-08-17 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0032_podcast_episodes_delete_podcastepisode"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
