# Generated by Django 4.2.2 on 2023-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0033_podcast_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listencheckin",
            name="progress",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
