# Generated by Django 4.2.2 on 2023-08-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0034_alter_listencheckin_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="listencheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_listen", "To Listen"),
                    ("looping", "Looping"),
                    ("listened", "Listened"),
                    ("listening", "Listening"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                ],
                max_length=255,
            ),
        ),
    ]
