# Generated by Django 4.2.2 on 2023-08-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0035_podcast_updated_at_alter_listencheckin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="categories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="explicit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="podcast",
            name="language",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
