# Generated by Django 4.2.2 on 2023-08-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0036_podcast_categories_podcast_copyright_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="explicit",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
