# Generated by Django 4.2.2 on 2023-08-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0038_podcast_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listencheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_listen", "To Listen"),
                    ("looping", "Looping"),
                    ("listened", "Listened"),
                    ("listening", "Listening"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("sampled", "Sampled"),
                ],
                max_length=255,
            ),
        ),
    ]
