# Generated by Django 4.2.2 on 2023-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0039_alter_listencheckin_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="isrc",
            new_name="catalog_number",
        ),
        migrations.AddField(
            model_name="track",
            name="isrc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
