# Generated by Django 4.2.2 on 2023-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0040_rename_isrc_release_catalog_number_track_isrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
