# Generated by Django 4.2.2 on 2023-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0041_release_other_titles_track_other_titles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="other_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
