# Generated by Django 4.2.2 on 2023-08-19 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0042_label_other_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="romanized_name",
        ),
    ]
