# Generated by Django 4.2.2 on 2023-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0043_remove_label_romanized_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="recording_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Studio", "Studio"),
                    ("Live", "Live"),
                    ("Studio and Live", "Studio and Live"),
                    ("Compilation", "Compilation"),
                    ("Bootleg", "Bootleg"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="release_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LP", "LP"),
                    ("EP", "EP"),
                    ("Single", "Single"),
                    ("Box Set", "Box Set"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
