# Generated by Django 4.2.2 on 2023-08-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0044_alter_release_recording_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
