# Generated by Django 4.2.2 on 2023-08-26 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0047_releasegroup_releaseingroup_releasegroup_releases_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releaseingroup",
            options={"ordering": ["release__release_date"]},
        ),
        migrations.RemoveField(
            model_name="releaseingroup",
            name="order",
        ),
    ]
