# Generated by Django 4.2.2 on 2023-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0048_alter_releaseingroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="recorded_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="recorded_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
