# Generated by Django 4.2.2 on 2023-09-13 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0049_track_recorded_date_work_recorded_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="label",
            old_name="history",
            new_name="notes",
        ),
    ]
