# Generated by Django 4.2.2 on 2023-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0050_rename_history_label_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="note",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="track",
            old_name="note",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="note",
            new_name="notes",
        ),
        migrations.RemoveField(
            model_name="label",
            name="note",
        ),
    ]
