# Generated by Django 4.2.2 on 2023-09-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0011_company"),
        ("listen", "0053_release_label_deprecated_alter_release_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiobook",
            name="publisher",
        ),
        migrations.AddField(
            model_name="audiobook",
            name="publisher_deprecated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audiobooks",
                to="entity.company",
            ),
        ),
    ]
