# Generated by Django 4.2.2 on 2023-09-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0038_book_publisher_deprecated_alter_book_publisher"),
        ("entity", "0011_company"),
        ("listen", "0054_remove_audiobook_publisher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiobook",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audiobooks",
                to="entity.company",
            ),
        ),
        migrations.AlterField(
            model_name="audiobook",
            name="publisher_deprecated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audiobooks",
                to="read.publisher",
            ),
        ),
    ]
