# Generated by Django 4.2.2 on 2023-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0056_alter_listencheckin_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiobook",
            old_name="details",
            new_name="notes",
        ),
    ]
