# Generated by Django 4.2.2 on 2023-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0057_rename_details_audiobook_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiobook",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="audiobookrole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="release",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="releaserole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="track",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="trackrole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="workrole",
            old_name="person",
            new_name="creator",
        ),
    ]
