# Generated by Django 4.2.2 on 2023-10-18 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0058_rename_persons_audiobook_creators_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="label_deprecated",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
    ]
