# Generated by Django 4.2.2 on 2023-10-18 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0059_remove_release_label_deprecated_delete_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiobook",
            name="publisher_deprecated",
        ),
    ]
