# Generated by Django 4.2.2 on 2023-10-21 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0060_remove_audiobook_publisher_deprecated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="kkbox_url",
        ),
        migrations.RemoveField(
            model_name="release",
            name="youtube_url",
        ),
    ]
