# Generated by Django 4.2.2 on 2023-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0061_remove_release_kkbox_url_remove_release_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listencheckin",
            name="progress_type",
            field=models.CharField(
                choices=[
                    ("TT", "Accumulated Listen Time"),
                    ("LT", "Loop Time"),
                    ("EP", "Episode"),
                ],
                default="LT",
                max_length=2,
            ),
        ),
    ]
