# Generated by Django 4.2.2 on 2023-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0062_alter_listencheckin_progress_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiobook",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="podcast",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="release",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="releasegroup",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="track",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="work",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
