# Generated by Django 4.2.2 on 2023-10-30 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0063_audiobook_locked_podcast_locked_release_locked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="romanized_title",
        ),
    ]
