# Generated by Django 4.2.2 on 2023-10-30 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0064_remove_work_romanized_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="romanized_title",
        ),
        migrations.RemoveField(
            model_name="track",
            name="romanized_title",
        ),
    ]
