# Generated by Django 4.2.2 on 2023-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0067_delete_historicalpodcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="listencheckin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
