# Generated by Django 4.2.2 on 2023-06-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
