# Generated by Django 4.2.2 on 2023-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="romanized_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="romanized_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
