# Generated by Django 4.2.2 on 2023-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="persons",
        ),
        migrations.RemoveField(
            model_name="book",
            name="works",
        ),
        migrations.AddField(
            model_name="book",
            name="work_roles",
            field=models.ManyToManyField(
                related_name="books", through="read.BookWorkRole", to="read.work"
            ),
        ),
    ]
