# Generated by Django 4.2.2 on 2023-06-19 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="description",
        ),
    ]
