# Generated by Django 4.2.2 on 2023-06-16 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="read.edition"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="read.person"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="read.role"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="edition",
            name="persons",
            field=models.ManyToManyField(
                related_name="editions", through="read.EditionRole", to="read.person"
            ),
        ),
    ]
