# Generated by Django 4.2.2 on 2023-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodical",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Daily"),
                    ("SW", "Semiweekly"),
                    ("W", "Weekly"),
                    ("BW", "Biweekly"),
                    ("SM", "Semimonthly"),
                    ("M", "Monthly"),
                    ("SQ", "Semiquarterly"),
                    ("BM", "Bimonthly"),
                    ("Q", "Quarterly"),
                    ("SA", "Semiannually"),
                    ("A", "Annually"),
                    ("B", "Biennially"),
                    ("T", "Triennially"),
                    ("Q", "Quadrennially"),
                    ("QQ", "Quinquennially"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
