# Generated by Django 4.2.2 on 2023-06-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0002_initial"),
        ("read", "0002_remove_book_persons_remove_book_works_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="persons",
            field=models.ManyToManyField(
                related_name="books", through="read.BookRole", to="entity.person"
            ),
        ),
        migrations.AddField(
            model_name="bookworkrole",
            name="publication_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
