# Generated by Django 4.2.2 on 2023-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0002_remove_work_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="work_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
