# Generated by Django 4.2.2 on 2023-06-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0002_person_romanized_name_publisher_romanized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
