# Generated by Django 4.2.2 on 2023-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("read", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcheckin",
            name="book",
        ),
        migrations.AddField(
            model_name="bookcheckin",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="bookcheckin",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
