# Generated by Django 4.2.2 on 2023-06-21 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0003_book_persons_bookworkrole_publication_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookrole",
            old_name="name",
            new_name="alt_name",
        ),
    ]
