# Generated by Django 4.2.2 on 2023-06-17 12:23

from django.db import migrations, models
import read.models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0003_edition_cover_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=read.models.rename_edition_cover
            ),
        ),
    ]
