# Generated by Django 4.2.2 on 2023-06-16 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0003_editionrole_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edition",
            old_name="name",
            new_name="edition_title",
        ),
    ]
