# Generated by Django 4.2.2 on 2023-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0003_edition_remove_book_work_roles_book_works_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editionrole",
            name="alt_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
