# Generated by Django 4.2.2 on 2023-06-27 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("write", "0001_initial"),
        ("read", "0003_remove_bookcheckin_book_bookcheckin_content_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookCheckIn",
            new_name="ReadCheckIn",
        ),
    ]
