# Generated by Django 4.2.2 on 2023-06-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
        ("read", "0003_work_language_work_work_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="edition_format",
            new_name="book_format",
        ),
        migrations.AddField(
            model_name="book",
            name="book_type",
            field=models.CharField(
                choices=[
                    ("SB", "Stand Alone Book"),
                    ("SS", "Short Stories Collection"),
                    ("ES", "Essays Collection"),
                ],
                default="SB",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="persons",
            field=models.ManyToManyField(
                related_name="books", through="read.BookRole", to="entity.person"
            ),
        ),
        migrations.AlterField(
            model_name="bookrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entity.person",
            ),
        ),
        migrations.AlterField(
            model_name="bookrole",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entity.role",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="persons",
            field=models.ManyToManyField(
                related_name="works", through="read.WorkRole", to="entity.person"
            ),
        ),
        migrations.AlterField(
            model_name="workrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entity.person",
            ),
        ),
        migrations.AlterField(
            model_name="workrole",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entity.role",
            ),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
