# Generated by Django 4.2.2 on 2023-06-21 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0004_rename_name_bookrole_alt_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookworkrole",
            old_name="name",
            new_name="alt_name",
        ),
    ]
