# Generated by Django 4.2.2 on 2023-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0004_rename_bookcheckin_readcheckin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_sens",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
