# Generated by Django 4.2.2 on 2023-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0004_rename_name_edition_edition_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
