# Generated by Django 4.2.2 on 2023-06-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0004_alter_edition_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="cover_sens",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="read.person",
            ),
        ),
    ]
