# Generated by Django 5.0 on 2023-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0004_alter_historicalwork_work_type_alter_work_work_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readcheckin",
            name="progress",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="readcheckin",
            name="progress_type",
            field=models.CharField(
                choices=[("PG", "Page"), ("PC", "Percentage"), ("CH", "Chapter")],
                default="PG",
                max_length=2,
            ),
        ),
    ]
