# Generated by Django 4.2.2 on 2023-06-25 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0005_remove_book_book_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="works",
        ),
    ]
