# Generated by Django 5.0.1 on 2024-01-11 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0006_historicalwork_related_locations_hierarchy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalIssueInstance",
        ),
    ]
