# Generated by Django 4.2.2 on 2023-06-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
        ("read", "0006_bookinseries_bookseries_bookinseries_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="persons",
            field=models.ManyToManyField(
                related_name="read_works", through="read.WorkRole", to="entity.person"
            ),
        ),
        migrations.AlterField(
            model_name="workrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_workrole_set",
                to="entity.person",
            ),
        ),
        migrations.AlterField(
            model_name="workrole",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_workrole_set",
                to="entity.role",
            ),
        ),
    ]
