# Generated by Django 4.2.2 on 2023-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0006_edition_edition_format_edition_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="asin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="isbn_10",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="isbn_13",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="edition",
            name="persons",
            field=models.ManyToManyField(
                related_name="editions", through="read.EditionRole", to="read.person"
            ),
        ),
    ]
