# Generated by Django 4.2.2 on 2023-06-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("write", "0001_initial"),
        ("read", "0006_book_book_subtitle_work_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_read", "To Read"),
                            ("currently_reading", "Currently Reading"),
                            ("finished_reading", "Finished Reading"),
                            ("paused", "Paused"),
                            ("abandoned", "Abandoned"),
                            ("rereading", "Rereading"),
                            ("finishied_rereading", "Finished Rereading"),
                        ],
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("comments_enabled", models.BooleanField(default=True)),
                ("share_on_feed", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="read.book"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="write.tag")),
            ],
        ),
    ]
