# Generated by Django 4.2.2 on 2023-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0007_bookcheckin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcheckin",
            name="progress",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
