# Generated by Django 5.0.1 on 2024-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0008_work_based_on_games_work_based_on_litworks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="based_on_litworks",
            field=models.ManyToManyField(
                blank=True, related_name="related_publications", to="read.work"
            ),
        ),
    ]
