# Generated by Django 4.2.2 on 2023-06-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0008_alter_book_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="publication_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
