# Generated by Django 4.2.2 on 2023-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0008_alter_bookcheckin_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcheckin",
            name="progress_type",
            field=models.CharField(
                choices=[("PG", "Page number"), ("PC", "Percentage")],
                default="PG",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bookcheckin",
            name="progress",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
