# Generated by Django 4.2.2 on 2023-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0009_bookcheckin_progress_type_alter_bookcheckin_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcheckin",
            name="progress",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
