# Generated by Django 5.0.1 on 2024-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0008_alter_historicalrelease_recording_type_and_more"),
        ("play", "0007_gamereleasedate_notes_and_more"),
        ("read", "0009_alter_work_based_on_litworks"),
        ("visit", "0016_historicallocation_osm_id_type_location_osm_id_type"),
        ("watch", "0010_historicalmoviereleasedate_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="mentioned_books",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="read.book"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_games",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="play.game"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_gameworks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="play.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_issues",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="read.issue"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_litinstances",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="read.instance"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_litworks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="read.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_publications",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_movies",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="watch.movie"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_musicalworks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="listen.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_periodicals",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_publications",
                to="read.periodical",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_releases",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_publications",
                to="listen.release",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_series",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="watch.series"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_tracks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_publications", to="listen.track"
            ),
        ),
    ]
