# Generated by Django 4.2.2 on 2023-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0009_alter_edition_publication_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edition",
            name="identifier",
        ),
        migrations.AlterField(
            model_name="edition",
            name="price",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
