# Generated by Django 4.2.2 on 2023-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0010_alter_bookcheckin_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcheckin",
            name="progress_type",
            field=models.CharField(
                choices=[("PG", "Page"), ("PC", "Percentage")],
                default="PG",
                max_length=2,
            ),
        ),
    ]
