# Generated by Django 4.2.2 on 2023-07-04 19:44

from django.db import migrations
import read.models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0010_issue_created_at_issue_created_by_issue_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn_10",
            field=read.models.ISBNField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn_13",
            field=read.models.ISBNField(blank=True, max_length=20, null=True),
        ),
    ]
