# Generated by Django 4.2.2 on 2023-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0011_alter_edition_asin_alter_edition_isbn_10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="price",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
