# Generated by Django 4.2.2 on 2023-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0011_alter_bookcheckin_progress_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcheckin",
            name="share_to_feed",
            field=models.BooleanField(default=True),
        ),
    ]
