# Generated by Django 4.2.2 on 2023-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0012_instance_created_at_instance_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="edition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
