# Generated by Django 4.2.2 on 2023-06-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0012_alter_edition_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="editionrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="read.person",
            ),
        ),
        migrations.AlterField(
            model_name="editionrole",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="read.role",
            ),
        ),
    ]
