# Generated by Django 4.2.2 on 2023-06-21 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0012_bookcheckin_share_to_feed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcheckin",
            name="share_on_feed",
        ),
    ]
