# Generated by Django 4.2.2 on 2023-06-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0013_edition_language_alter_editionrole_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrole",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="read.role",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="death_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
