# Generated by Django 4.2.2 on 2023-06-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0005_remove_awardinstance_award_and_more"),
        ("read", "0014_alter_bookcheckin_share_to_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_read", "To Read"),
                    ("currently_reading", "Currently Reading"),
                    ("finished_reading", "Finished Reading"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("rereading", "Rereading"),
                    ("finished_rereading", "Finished Rereading"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="bookrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="book_roles",
                to="entity.person",
            ),
        ),
        migrations.AlterField(
            model_name="bookworkrole",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="book_work_roles",
                to="entity.person",
            ),
        ),
    ]
