# Generated by Django 4.2.2 on 2023-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0016_alter_work_work_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_read", "To Read"),
                    ("reading", "Reading"),
                    ("finished_reading", "Read"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("rereading", "Rereading"),
                    ("reread", "Reread"),
                    ("afterthoughts", "Afterthoughts"),
                ],
                max_length=255,
            ),
        ),
    ]
