# Generated by Django 4.2.2 on 2023-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0017_alter_readcheckin_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="work",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="read_works", to="read.genre"
            ),
        ),
    ]
