# Generated by Django 4.2.2 on 2023-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0018_genre_work_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="work_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO", "Novel"),
                    ("NV", "Novella"),
                    ("SS", "Short Story"),
                    ("PM", "Poem"),
                    ("PL", "Play"),
                    ("SC", "Screenplay"),
                    ("NF", "Nonfiction"),
                    ("OT", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
