# Generated by Django 4.2.2 on 2023-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0019_alter_work_work_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
