# Generated by Django 4.2.2 on 2023-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0021_workrole_alt_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodical",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
