# Generated by Django 4.2.2 on 2023-08-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0022_periodical_wikipedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodical",
            name="publisher",
        ),
        migrations.AddField(
            model_name="issue",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_issues",
                to="read.publisher",
            ),
        ),
    ]
