# Generated by Django 4.2.2 on 2023-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0024_work_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="internet_archive_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
