# Generated by Django 4.2.2 on 2023-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0025_book_internet_archive_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="internet_archive_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
