# Generated by Django 4.2.2 on 2023-08-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0026_issue_internet_archive_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
