# Generated by Django 4.2.2 on 2023-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0027_work_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="other_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
