# Generated by Django 4.2.2 on 2023-08-19 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0028_publisher_other_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="romanized_name",
        ),
    ]
