# Generated by Django 4.2.2 on 2023-08-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0029_remove_publisher_romanized_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="publication_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="publication_date",
            field=models.TextField(blank=True, null=True),
        ),
    ]
