# Generated by Django 4.2.2 on 2023-08-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0030_alter_instance_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.TextField(blank=True, null=True),
        ),
    ]
