# Generated by Django 4.2.2 on 2023-08-22 15:10

from django.db import migrations
import read.models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0031_alter_book_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="eisbn_13",
            field=read.models.ISBNField(blank=True, max_length=20, null=True),
        ),
    ]
