# Generated by Django 4.2.2 on 2023-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0032_book_eisbn_13"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
