# Generated by Django 4.2.2 on 2023-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0033_book_wikipedia_instance_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookseries",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
