# Generated by Django 4.2.2 on 2023-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0036_rename_history_publisher_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="note",
        ),
    ]
