# Generated by Django 4.2.2 on 2023-09-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0011_company"),
        ("read", "0037_remove_publisher_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher_deprecated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="read.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="entity.company",
            ),
        ),
    ]
