# Generated by Django 4.2.2 on 2023-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0038_book_publisher_deprecated_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readcheckin",
            name="progress_type",
            field=models.CharField(
                choices=[("PG", "Page"), ("PC", "Percentage"), ("CH", "Chapter")],
                default="PG",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="readcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_read", "To Read"),
                    ("reading", "Reading"),
                    ("finished_reading", "Read"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("rereading", "Rereading"),
                    ("reread", "Reread"),
                    ("afterthought", "Afterthought"),
                    ("sampled", "Sampled"),
                    ("skimmed", "Skimmed"),
                ],
                max_length=255,
            ),
        ),
    ]
