# Generated by Django 4.2.2 on 2023-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0039_alter_readcheckin_progress_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="details",
            new_name="notes",
        ),
    ]
