# Generated by Django 4.2.2 on 2023-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0040_rename_details_book_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="bookrole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="instance",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="instancerole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="workrole",
            old_name="person",
            new_name="creator",
        ),
    ]
