# Generated by Django 4.2.2 on 2023-10-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0013_rename_person_creator"),
        ("listen", "0060_remove_audiobook_publisher_deprecated"),
        ("read", "0041_rename_persons_book_creators_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publisher_deprecated",
        ),
        migrations.AlterField(
            model_name="issue",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_issues",
                to="entity.company",
            ),
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
