# Generated by Django 4.2.2 on 2023-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0042_remove_book_publisher_deprecated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readcheckin",
            name="progress_type",
            field=models.CharField(
                choices=[("PG", "Page"), ("PC", "Percentage")],
                default="PG",
                max_length=2,
            ),
        ),
    ]
