# Generated by Django 4.2.2 on 2023-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0043_alter_readcheckin_progress_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="locked",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
