# Generated by Django 4.2.2 on 2023-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0044_work_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookseries",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instance",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodical",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="work",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
