# Generated by Django 4.2.2 on 2023-11-05 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0046_historicalworkrole_historicalwork_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookseries",
            old_name="description",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="historicalbookseries",
            old_name="description",
            new_name="notes",
        ),
    ]
