# Generated by Django 4.2.2 on 2023-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0047_rename_description_bookseries_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="readcheckin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
