# Generated by Django 4.2.2 on 2023-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0048_readcheckin_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalBookInstance",
        ),
    ]
