# Generated by Django 4.2.2 on 2023-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerole",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
