# Generated by Django 4.2.2 on 2023-06-26 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("write", "0001_initial"),
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecheckin",
            name="tags",
            field=models.ManyToManyField(blank=True, to="write.tag"),
        ),
        migrations.AddField(
            model_name="gamecheckin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="developers",
            field=models.ManyToManyField(related_name="games", to="play.developer"),
        ),
        migrations.AddField(
            model_name="game",
            name="persons",
            field=models.ManyToManyField(
                related_name="games", through="play.GameRole", to="entity.person"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(related_name="games", to="play.platform"),
        ),
        migrations.AddField(
            model_name="game",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
