# Generated by Django 4.2.2 on 2023-06-23 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0002_gamerole_alt_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="subtitle",
            new_name="romanized_title",
        ),
    ]
