# Generated by Django 4.2.2 on 2023-06-29 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("play", "0004_gameinseries_series_gameinseries_series"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Series",
            new_name="GameSeries",
        ),
    ]
