# Generated by Django 4.2.2 on 2023-06-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0004_rename_developer_game_developers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamecheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_play", "To Play"),
                    ("playing", "Playing"),
                    ("played", "Played"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("replaying", "Replaying"),
                    ("replayed", "Replayed"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="gamerole",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gameroles",
                to="play.game",
            ),
        ),
    ]
