# Generated by Django 5.0.1 on 2024-01-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0004_historicalwork_setting_locations_hierarchy_and_more"),
        ("read", "0008_work_based_on_games_work_based_on_litworks_and_more"),
        ("watch", "0008_remove_historicalmovie_based_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="based_on_games",
            field=models.ManyToManyField(blank=True, to="play.work"),
        ),
        migrations.AddField(
            model_name="work",
            name="based_on_litworks",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="read.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="based_on_movies",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="watch.movie"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="based_on_series",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="watch.series"
            ),
        ),
    ]
