# Generated by Django 4.2.2 on 2023-07-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
        ("play", "0005_rename_series_gameseries"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamecasts",
                        to="play.game",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity.role",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="casts",
            field=models.ManyToManyField(
                related_name="games_casts", through="play.GameCast", to="entity.person"
            ),
        ),
    ]
