# Generated by Django 4.2.2 on 2023-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
        ("play", "0006_gamecast_game_casts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="casts",
            field=models.ManyToManyField(
                related_name="games_cast", through="play.GameCast", to="entity.person"
            ),
        ),
    ]
