# Generated by Django 5.0.1 on 2024-01-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0006_alter_work_based_on_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamereleasedate",
            name="notes",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicalgamereleasedate",
            name="notes",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
