# Generated by Django 4.2.2 on 2023-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0007_alter_game_casts"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platform",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
