# Generated by Django 5.0.1 on 2024-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0009_alter_historicalreleasetrack_disk_and_more"),
        ("play", "0007_gamereleasedate_notes_and_more"),
        ("read", "0010_work_mentioned_books_work_mentioned_games_and_more"),
        ("visit", "0016_historicallocation_osm_id_type_location_osm_id_type"),
        ("watch", "0012_episode_based_on_games_episode_based_on_litworks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="mentioned_books",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="read.book"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_games",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="play.game"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_gameworks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="play.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_issues",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="read.issue"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_litinstances",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="read.instance"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_litworks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="read.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_locations",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="visit.location"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_movies",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="watch.movie"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_musicalworks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="listen.work"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_periodicals",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="read.periodical"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_releases",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="listen.release"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_series",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="watch.series"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="mentioned_tracks",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_gameworks", to="listen.track"
            ),
        ),
    ]
