# Generated by Django 5.0.1 on 2024-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listen", "0009_alter_historicalreleasetrack_disk_and_more"),
        ("play", "0008_work_mentioned_books_work_mentioned_games_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ending_songs",
            field=models.ManyToManyField(
                blank=True, related_name="games_as_ending_song", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="soundtracks",
            field=models.ManyToManyField(
                blank=True, related_name="games_with_soundtrack", to="listen.release"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="theme_songs",
            field=models.ManyToManyField(
                blank=True, related_name="games_as_theme_song", to="listen.track"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="games_featuring_track", to="listen.track"
            ),
        ),
    ]
