# Generated by Django 4.2.2 on 2023-07-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entity", "0002_person_note"),
        ("play", "0008_developer_note_platform_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "first_release_date",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visual_novel", "Visual Novel"),
                            ("rpg", "RPG"),
                            ("action", "Action"),
                            ("adventure", "Adventure"),
                            ("platformer", "Platformer"),
                            ("puzzle", "Puzzle"),
                            ("racing", "Racing"),
                            ("fps", "FPS"),
                            ("tbs", "TBS"),
                            ("rts", "RTS"),
                            ("sports", "Sports"),
                            ("simulation", "Simulation"),
                            ("strategy", "Strategy"),
                            ("mmorpg", "MMORPG"),
                            ("sandbox", "Sandbox"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="play_works_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "developers",
                    models.ManyToManyField(
                        related_name="play_works", to="play.developer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_workrole_set",
                        to="entity.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_workrole_set",
                        to="entity.role",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.work"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="work",
            name="persons",
            field=models.ManyToManyField(
                related_name="play_works", through="play.WorkRole", to="entity.person"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="play_works_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="play.work",
            ),
        ),
    ]
