# Generated by Django 5.0.1 on 2024-07-17 11:59

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


def migrate_existing_works(apps, schema_editor):
    Game = apps.get_model("play", "Game")
    GameWork = apps.get_model("play", "GameWork")

    for game in Game.objects.all():
        if game.work:
            GameWork.objects.create(game=game, work=game.work, order=1)


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0010_playcheckin_visibility_playcheckin_visible_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="work",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_deprecated",
                to="play.work",
            ),
        ),
        migrations.CreateModel(
            name="GameWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "game",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.game"
                    ),
                ),
                (
                    "work",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="play.work",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="works",
            field=models.ManyToManyField(
                related_name="games", through="play.GameWork", to="play.work"
            ),
        ),
        migrations.RunPython(migrate_existing_works),
        migrations.RemoveField(
            model_name="game",
            name="work",
        ),
    ]
