# Generated by Django 5.0.1 on 2024-08-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0011_alter_game_work_gamework_game_works"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgame",
            name="work",
        ),
    ]
