# Generated by Django 4.2.2 on 2023-07-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0013_rename_publisher_game_publishers"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="romanized_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
