# Generated by Django 4.2.2 on 2023-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0014_game_subtitle_work_romanized_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamecheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_play", "To Play"),
                    ("playing", "Playing"),
                    ("played", "Played"),
                    ("paused", "Paused"),
                    ("abandoned", "Abandoned"),
                    ("replaying", "Replaying"),
                    ("replayed", "Replayed"),
                    ("afterthoughts", "Afterthoughts"),
                ],
                max_length=255,
            ),
        ),
    ]
