# Generated by Django 4.2.2 on 2023-07-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0016_genre_work_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
