# Generated by Django 4.2.2 on 2023-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0017_genre_slug_alter_genre_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamepublisher",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="developer",
            name="closed_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="developer",
            name="founded_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="developer",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamepublisher",
            name="closed_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="gamepublisher",
            name="founded_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="gamepublisher",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
