# Generated by Django 4.2.2 on 2023-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0018_developer_wikipedia_gamepublisher_wikipedia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
