# Generated by Django 4.2.2 on 2023-08-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0019_work_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
