# Generated by Django 4.2.2 on 2023-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0020_game_other_titles_work_other_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="other_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamepublisher",
            name="other_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platform",
            name="other_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
