# Generated by Django 4.2.2 on 2023-08-19 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0021_developer_other_names_gamepublisher_other_names_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="romanized_name",
        ),
        migrations.RemoveField(
            model_name="gamepublisher",
            name="romanized_name",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="romanized_name",
        ),
    ]
