# Generated by Django 4.2.2 on 2023-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0022_remove_developer_romanized_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="rating",
            field=models.TextField(blank=True, null=True),
        ),
    ]
