# Generated by Django 4.2.2 on 2023-09-07 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0025_work_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="description",
            new_name="notes",
        ),
    ]
