# Generated by Django 4.2.2 on 2023-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0027_rename_history_developer_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="note",
        ),
        migrations.RemoveField(
            model_name="gamepublisher",
            name="note",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="note",
        ),
    ]
