# Generated by Django 4.2.2 on 2023-09-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0028_remove_developer_note_remove_gamepublisher_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
