# Generated by Django 4.2.2 on 2023-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0011_company"),
        ("play", "0031_gamecompany_game_developers_game_publishers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="developers_deprecated",
            field=models.ManyToManyField(
                related_name="developed_games_deprecated", to="play.gamecompany"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="publishers_deprecated",
            field=models.ManyToManyField(
                related_name="published_games_deprecated", to="play.gamecompany"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="developers_deprecated",
            field=models.ManyToManyField(
                related_name="play_works_deprecated", to="play.gamecompany"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="developers",
            field=models.ManyToManyField(
                related_name="developed_games", to="entity.company"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="publishers",
            field=models.ManyToManyField(
                related_name="published_games", to="entity.company"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="developers",
            field=models.ManyToManyField(
                related_name="play_works", to="entity.company"
            ),
        ),
    ]
