# Generated by Django 4.2.2 on 2023-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0032_game_developers_deprecated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameseries",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
