# Generated by Django 4.2.2 on 2023-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0033_gameseries_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameseries",
            name="other_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameseries",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
