# Generated by Django 4.2.2 on 2023-09-29 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0034_gameseries_other_titles_gameseries_wikipedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="developers_deprecated",
        ),
        migrations.RemoveField(
            model_name="game",
            name="publishers_deprecated",
        ),
        migrations.RemoveField(
            model_name="work",
            name="developers_deprecated",
        ),
        migrations.DeleteModel(
            name="GameCompany",
        ),
    ]
