# Generated by Django 4.2.2 on 2023-09-30 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0036_gamereleasedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="release_date",
        ),
    ]
