# Generated by Django 4.2.2 on 2023-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0037_remove_game_release_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="gamecast",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="gamerole",
            old_name="person",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="persons",
            new_name="creators",
        ),
        migrations.RenameField(
            model_name="workrole",
            old_name="person",
            new_name="creator",
        ),
    ]
