# Generated by Django 4.2.2 on 2023-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0039_remove_gamepublisher_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gameseries",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platform",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="work",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
