# Generated by Django 4.2.2 on 2023-10-30 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0040_game_locked_gameseries_locked_platform_locked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="romanized_title",
        ),
        migrations.RemoveField(
            model_name="work",
            name="romanized_title",
        ),
    ]
