# Generated by Django 4.2.2 on 2023-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0043_historicalwork_historicalgameseries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecheckin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
