# Generated by Django 4.2.2 on 2023-11-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("play", "0045_rename_gamecheckin_playcheckin"),
    ]

    operations = [
        migrations.AddField(
            model_name="playcheckin",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="playcheckin",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
