# Generated by Django 4.2.2 on 2023-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0002_vote_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="value",
            field=models.SmallIntegerField(
                choices=[(1, "Upvote"), (-1, "Downvote")], default=1
            ),
            preserve_default=False,
        ),
    ]
