# Generated by Django 5.0 on 2023-12-30 19:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location_new",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="birth_location",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="birth_location",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="death_location",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="death_location",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="location_new",
            field=auto_prefetch.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="birth_location",
            field=auto_prefetch.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="death_location",
            field=auto_prefetch.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="visit.location",
            ),
        ),
    ]
