# Generated by Django 4.2.2 on 2023-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
