# Generated by Django 5.0 on 2023-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0002_company_location_new_creator_birth_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="birth_location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="death_location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="birth_location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="death_location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
