# Generated by Django 4.2.2 on 2023-06-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="bio",
        ),
        migrations.AddField(
            model_name="person",
            name="birth_place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="death_place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="wikipedia",
            field=models.URLField(blank=True, null=True),
        ),
    ]
