# Generated by Django 4.2.2 on 2023-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0003_alter_role_name_alter_role_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="other_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
