# Generated by Django 5.0 on 2023-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0003_creator_birth_location_hierarchy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
