# Generated by Django 5.0.1 on 2024-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0004_company_location_hierarchy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="location",
        ),
        migrations.RemoveField(
            model_name="historicalcompany",
            name="location",
        ),
    ]
