# Generated by Django 5.0.1 on 2024-01-05 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0005_remove_company_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="location_new",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="historicalcompany",
            old_name="location_new",
            new_name="location",
        ),
    ]
