# Generated by Django 5.0.1 on 2024-01-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0006_rename_location_new_company_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="entity.company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predecessor",
                to="entity.company",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entity.company",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entity.company",
            ),
        ),
    ]
