# Generated by Django 5.0.1 on 2024-01-16 18:48

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0007_company_parent_company_successor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="company",
            name="successor",
        ),
        migrations.RemoveField(
            model_name="historicalcompany",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicalcompany",
            name="successor",
        ),
        migrations.CreateModel(
            name="CompanyParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_name", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.CharField(blank=True, max_length=10, null=True)),
                ("end_date", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "child",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_companies",
                        to="entity.company",
                    ),
                ),
                (
                    "parent",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_companies",
                        to="entity.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPastName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.CharField(blank=True, max_length=10, null=True)),
                ("end_date", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "company",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_names",
                        to="entity.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
