# Generated by Django 4.2.2 on 2023-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0007_remove_person_romanized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
