# Generated by Django 4.2.2 on 2023-08-20 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0008_person_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="notes",
        ),
    ]
