# Generated by Django 4.2.2 on 2023-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0009_remove_person_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="note",
            new_name="notes",
        ),
    ]
