# Generated by Django 5.0.1 on 2024-01-20 09:11

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0009_memberof"),
        ("visit", "0016_historicallocation_osm_id_type_location_osm_id_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="birth_place",
        ),
        migrations.RemoveField(
            model_name="creator",
            name="death_place",
        ),
        migrations.RemoveField(
            model_name="historicalcreator",
            name="birth_place",
        ),
        migrations.RemoveField(
            model_name="historicalcreator",
            name="death_place",
        ),
        migrations.AddField(
            model_name="creator",
            name="active_years",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="origin_location",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_location",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="origin_location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="active_years",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="origin_location",
            field=auto_prefetch.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="visit.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalcreator",
            name="origin_location_hierarchy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
