# Generated by Django 5.0.1 on 2024-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0010_remove_creator_birth_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="active_years",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcreator",
            name="active_years",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
