# Generated by Django 4.2.2 on 2023-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0011_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="creator_type",
            field=models.CharField(
                blank=True,
                choices=[("person", "Person"), ("group", "Group")],
                default="person",
                max_length=10,
                null=True,
            ),
        ),
    ]
