# Generated by Django 5.0.1 on 2024-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0011_alter_creator_active_years_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="role",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="role",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Performing Artists", "Performing Artists"),
                    ("Composition and Lyrics", "Composition and Lyrics"),
                    ("Production and Engineering", "Production and Engineering"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "domain", "category")},
        ),
    ]
