# Generated by Django 4.2.2 on 2023-10-18 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0041_rename_persons_book_creators_and_more"),
        ("watch", "0029_rename_persons_episode_creators_and_more"),
        ("play", "0038_rename_persons_game_creators_and_more"),
        ("listen", "0058_rename_persons_audiobook_creators_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entity", "0012_person_creator_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Creator",
        ),
    ]
