# Generated by Django 4.2.2 on 2023-10-21 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0013_rename_person_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="closed_date",
            new_name="defunct_date",
        ),
    ]
