# Generated by Django 4.2.2 on 2023-10-30 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0016_historicalcreator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalCreator",
        ),
    ]
