# Generated by Django 4.1.7 on 2023-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="followed_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
