# Generated by Django 4.2.2 on 2023-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Repost",
        ),
    ]
