# Generated by Django 5.0.1 on 2024-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PU", "Public"),
                    ("ME", "Mentioned"),
                    ("FO", "Followers"),
                    ("MF", "Mutual Friends"),
                    ("PR", "Private"),
                ],
                default="VISIBILITY_PUBLIC",
                max_length=2,
            ),
        ),
    ]
