# Generated by Django 4.1.7 on 2023-06-12 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0002_activity_followed_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="followed_username",
        ),
    ]
