# Generated by Django 4.2.2 on 2023-06-14 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0003_activity_reposted_by_activity_reposted_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="reposted_by",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="reposted_from",
        ),
    ]
