# Generated by Django 4.2.2 on 2023-06-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0004_remove_activity_reposted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="repost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="activity_feed.activity",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="repost_comment",
            field=models.TextField(blank=True),
        ),
    ]
