# Generated by Django 5.0 on 2023-12-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("altprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AltProfileTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("html_content", models.TextField()),
                ("css_content", models.TextField()),
            ],
        ),
    ]
