# Generated by Django 5.0 on 2023-12-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("altprofile", "0002_altprofiletemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="altprofile",
            name="custom_css",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="altprofile",
            name="custom_html",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="altprofiletemplate",
            name="css_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="altprofiletemplate",
            name="html_content",
            field=models.TextField(blank=True),
        ),
    ]
