# Generated by Django 4.2.2 on 2023-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("mention", "Mention"),
                    ("repost", "Repost"),
                    ("follow", "Follow"),
                ],
                max_length=20,
            ),
        ),
    ]
