# Generated by Django 4.2.2 on 2023-10-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notify", "0002_mutednotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="subject_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_subjects",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="subject_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("mention", "Mention"),
                    ("repost", "Repost"),
                    ("delete", "Delete"),
                ],
                max_length=20,
            ),
        ),
    ]
