# Generated by Django 4.2.2 on 2023-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0003_notification_subject_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("mention", "Mention"),
                    ("repost", "Repost"),
                    ("follow", "Follow"),
                    ("delete", "Delete"),
                ],
                max_length=200,
            ),
        ),
    ]
